#!/bin/bash
# Pull fresh code from upstream master, push to origin master

BRANCH="${1:-master}"
REV="$(git rev-parse "$BRANCH")"
if [[ -z "$REV" ]]; then
	exit $?;
fi
if [[ "$(git rev-parse HEAD)" == "$REV" ]]; then
	# already on $BRANCH
	git pull --ff-only upstream "$BRANCH"
else
	git fetch upstream "$BRANCH":"$BRANCH"
fi
if [[ $? ]]; then
	git push origin "$BRANCH":"$BRANCH"
fi
